# Generated by Django 4.1 on 2023-07-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProdcuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Creada', models.DateField(auto_now_add=True)),
                ('Actualizada', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CategoriaProdcuto',
                'verbose_name_plural': 'CategoriaProdcutos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='TiendaApp')),
                ('Precio', models.FloatField()),
                ('Disponibilidad', models.BooleanField(default=True)),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.categoriaprodcuto')),
            ],
            options={
                'verbose_name': 'Prodcuto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
