# Generated by Django 4.1 on 2023-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiciosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='ContenidoServicio',
            field=models.CharField(max_length=100, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='FechaActualizacionServicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='FechaCreacionServicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Imagen',
            field=models.ImageField(upload_to=None, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='NombreServicio',
            field=models.CharField(max_length=50, verbose_name='Servicio'),
        ),
    ]
