# Generated by Django 4.1 on 2023-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiciosApp', '0002_alter_servicio_contenidoservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Imagen',
            field=models.ImageField(upload_to='ServiciosApp', verbose_name='Imagen'),
        ),
    ]
